SET ECHO OFF

PROMPT ***** Employment Length *****
SELECT EMPLOYEE_FNAME||' '||EMPLOYEE_LNAME AS "Employee", SYSDATE - EMPLOYEE_HIREDATE AS "Days Employed" 
FROM EMPLOYEE, DUAL 
ORDER BY "Days Employed" DESC;

PROMPT
PROMPT ***** Number of Customers Per Employee *****
SELECT EMPLOYEE_ID AS "Employee ID",COUNT(CUSTOMER_ID) AS "Customers" 
FROM CUSTOMER 
GROUP BY EMPLOYEE_ID 
ORDER BY EMPLOYEE_ID ASC;

PROMPT
PROMPT ***** Employee Sales *****
COLUMN "Total Sales" FORMAT $999,999.90
SELECT E.EMPLOYEE_LNAME "Last Name", E.EMPLOYEE_FNAME AS "First Name", SUM(T.SUMMED) AS "Total Sales"
FROM CUSTOMER C, EMPLOYEE E,
(SELECT O.CUSTOMER_ID AS CUST_ID,SUM(I.QUANTITY * P.PRODUCT_PPU) AS SUMMED
FROM ORDERS O, INVOICE I, PRODUCT P
WHERE O.INVOICE_NUM = I.INVOICE_NUM
AND P.PRODUCT_ID = I.PRODUCT_ID
GROUP BY O.CUSTOMER_ID) T
WHERE C.CUSTOMER_ID = T.CUST_ID
AND C.EMPLOYEE_ID = E.EMPLOYEE_ID
GROUP BY E.EMPLOYEE_LNAME, E.EMPLOYEE_FNAME
ORDER BY E.EMPLOYEE_LNAME, E.EMPLOYEE_FNAME;

PROMPT
PROMPT ***** Units Sold by Product *****
SELECT PRODUCT.PRODUCT_NAME AS "Product Name", SUM(INVOICE.QUANTITY) AS "Units Sold"
FROM PRODUCT, INVOICE
WHERE PRODUCT.PRODUCT_ID = INVOICE.PRODUCT_ID
GROUP BY PRODUCT.PRODUCT_NAME
ORDER BY PRODUCT.PRODUCT_NAME ASC;

PROMPT
PROMPT ***** Lowest Selling Product *****
SELECT P.PRODUCT_NAME AS "Product Name", T.SUMMED AS "Quantity"
FROM PRODUCT P,(
SELECT PRODUCT_ID, SUM(QUANTITY) AS SUMMED
FROM INVOICE
GROUP BY PRODUCT_ID
HAVING SUM(QUANTITY) = 
(SELECT MIN(SUMMED)
FROM
(SELECT PRODUCT_ID, SUM(QUANTITY) AS SUMMED
FROM INVOICE
GROUP BY PRODUCT_ID))) T
WHERE P.PRODUCT_ID = T.PRODUCT_ID;

PROMPT
PROMPT ***** Highest Selling Product *****
SELECT P.PRODUCT_NAME AS "Product Name", T.SUMMED AS "Quantity"
FROM PRODUCT P,(
SELECT PRODUCT_ID, SUM(QUANTITY) AS SUMMED
FROM INVOICE
GROUP BY PRODUCT_ID
HAVING SUM(QUANTITY) = 
(SELECT MAX(SUMMED)
FROM
(SELECT PRODUCT_ID, SUM(QUANTITY) AS SUMMED
FROM INVOICE
GROUP BY PRODUCT_ID))) T
WHERE P.PRODUCT_ID = T.PRODUCT_ID;

PROMPT
PROMPT ***** Average Invoice Total *****
COLUMN "Average Sale" FORMAT $999,999.90
SELECT AVG(SUM(INVOICE.QUANTITY * PRODUCT.PRODUCT_PPU)) AS "Average Sale"
FROM  INVOICE, PRODUCT
WHERE INVOICE.PRODUCT_ID = PRODUCT.PRODUCT_ID
GROUP BY INVOICE.INVOICE_NUM;

PROMPT
PROMPT ***** Orders in Last 7 Days *****
SELECT DISTINCT ORDERS.INVOICE_NUM AS "Invoice #", ORDER_DATE AS "Date", CUSTOMER_COMPANY AS "Customer", EMPLOYEE_FNAME||' '||EMPLOYEE_LNAME AS "Employee", TO_CHAR(TOTAL.COST, '$999,999,999.99') AS "Cost"
FROM CUSTOMER, EMPLOYEE, ORDERS, INVOICE, PRODUCT, DUAL,
(SELECT INVOICE_NUM,SUM(QUANTITY * PRODUCT_PPU) AS "COST" FROM INVOICE,PRODUCT WHERE INVOICE.PRODUCT_ID = PRODUCT.PRODUCT_ID GROUP BY INVOICE_NUM) TOTAL
WHERE ORDERS.INVOICE_NUM = INVOICE.INVOICE_NUM AND TOTAL.INVOICE_NUM = ORDERS.INVOICE_NUM AND ORDERS.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID AND CUSTOMER.EMPLOYEE_ID = EMPLOYEE.EMPLOYEE_ID AND SYSDATE - ORDER_DATE < 7
ORDER BY ORDERS.INVOICE_NUM ASC;

PROMPT
PROMPT ***** Most Popular Product for Companies in California *****
SELECT PRODUCT_ID AS "Product ID", PRODUCT_NAME AS "Product Name" 
FROM PRODUCT WHERE PRODUCT_ID = (SELECT PRODUCT_ID FROM INVOICE 
WHERE QUANTITY = (SELECT MAX(QUANTITY) FROM INVOICE) AND INVOICE_NUM IN (SELECT INVOICE_NUM FROM ORDERS WHERE CUSTOMER_ID IN (SELECT CUSTOMER_ID FROM CUSTOMER WHERE CUSTOMER_STATE = 'CA')));

PROMPT
PROMPT ***** Customers Over $100k in Total Orders  *****
COLUMN "Total Orders" FORMAT $999,999.90
SELECT C.CUSTOMER_COMPANY AS "Company Name", T.SUMMED AS "Total Orders"
FROM CUSTOMER C,
(SELECT O.CUSTOMER_ID AS CUST_ID,SUM(I.QUANTITY * P.PRODUCT_PPU) AS SUMMED
FROM ORDERS O, INVOICE I, PRODUCT P
WHERE O.INVOICE_NUM = I.INVOICE_NUM
AND P.PRODUCT_ID = I.PRODUCT_ID
GROUP BY CUSTOMER_ID
HAVING SUM(I.QUANTITY * P.PRODUCT_PPU) > 100000) T
WHERE C.CUSTOMER_ID = T.CUST_ID
ORDER BY C.CUSTOMER_COMPANY;