SET ECHO OFF

PROMPT *** Employment Length ***
SELECT EMPLOYEE_FNAME||' '||EMPLOYEE_LNAME AS "Employee", SYSDATE - EMPLOYEE_HIREDATE AS "Days Employed" FROM EMPLOYEE, DUAL ORDER BY "Days Employed" DESC;

PROMPT *** Orders in Last 7 Days ***
SELECT INVOICE_NUM AS "Invoice #", ORDER_DATE AS "Date", CUSTOMER_COMPANY AS "Customer", EMPLOYEE_FNAME||' '||EMPLOYEE_LNAME AS "Employee",PRODUCT_NAME AS "Product", QUANTITY AS "Quantity", TO_CHAR(QUANTITY * PRODUCT_PPU, '$9,999.99') AS "Cost" FROM CUSTOMER, EMPLOYEE, ORDERS, PRODUCT, DUAL WHERE ORDERS.PRODUCT_ID = PRODUCT.PRODUCT_ID AND ORDERS.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID AND ORDERS.EMPLOYEE_ID = EMPLOYEE.EMPLOYEE_ID AND SYSDATE - ORDER_DATE < 7;

PROMPT *** Orders by Employee ID ***
ACCEPT eID PROMPT "Enter employee id: ";
SELECT EMPLOYEE_ID AS "ID",EMPLOYEE_FNAME||' '||EMPLOYEE_LNAME AS "Name" FROM EMPLOYEE WHERE EMPLOYEE_ID = '&eID';
PROMPT Orders:
SELECT INVOICE_NUM AS "Invoice#", PRODUCT_NAME AS "Product", CUSTOMER_COMPANY AS "Customer", QUANTITY AS "Qty", ORDER_DATE AS "Date", TO_CHAR(QUANTITY * PRODUCT_PPU, '$999,999.99') AS "Total" FROM ORDERS, CUSTOMER, PRODUCT WHERE ORDERS.EMPLOYEE_ID = '&eID' AND PRODUCT.PRODUCT_ID = ORDERS.PRODUCT_ID AND ORDERS.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID ORDER BY ORDER_DATE ASC;