SET ECHO OFF
SET VERIFY OFF

PROMPT *** Employment Length ***
SELECT EMPLOYEE_FNAME||' '||EMPLOYEE_LNAME AS "Employee", SYSDATE - EMPLOYEE_HIREDATE AS "Days Employed" FROM EMPLOYEE, DUAL ORDER BY "Days Employed" DESC;

PROMPT *** Orders in Last 7 Days ***
SELECT ORDERS.INVOICE_NUM AS "Invoice #", ORDER_DATE AS "Date", CUSTOMER_COMPANY AS "Customer", EMPLOYEE_FNAME||' '||EMPLOYEE_LNAME AS "Employee",PRODUCT_NAME AS "Product", QUANTITY AS "Quantity", TO_CHAR(QUANTITY * PRODUCT_PPU, '$9,999.99') AS "Cost" FROM CUSTOMER, EMPLOYEE, ORDERS, INVOICE, PRODUCT, DUAL WHERE ORDERS.INVOICE_NUM = INVOICE.INVOICE_NUM AND INVOICE.PRODUCT_ID = PRODUCT.PRODUCT_ID AND ORDERS.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID AND CUSTOMER.EMPLOYEE_ID = EMPLOYEE.EMPLOYEE_ID AND SYSDATE - ORDER_DATE < 7;

PROMPT *** Orders by Employee ID ***
ACCEPT eID PROMPT "Enter employee id: ";
SELECT EMPLOYEE_ID AS "ID",EMPLOYEE_FNAME||' '||EMPLOYEE_LNAME AS "Name" FROM EMPLOYEE WHERE EMPLOYEE_ID = '&eID';
PROMPT Orders:
SELECT ORDERS.INVOICE_NUM AS "Invoice#", PRODUCT_NAME AS "Product", CUSTOMER_COMPANY AS "Customer", QUANTITY AS "Qty", ORDER_DATE AS "Date", TO_CHAR(QUANTITY * PRODUCT_PPU, '$999,999.99') AS "Total" FROM ORDERS, CUSTOMER, PRODUCT, INVOICE WHERE CUSTOMER.EMPLOYEE_ID = '&eID' AND ORDERS.INVOICE_NUM = INVOICE.INVOICE_NUM AND PRODUCT.PRODUCT_ID = INVOICE.PRODUCT_ID AND ORDERS.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID ORDER BY ORDER_DATE ASC;

PROMPT *** Number of Customers Per Employee ***
SELECT EMPLOYEE_ID AS "Employee ID",COUNT(CUSTOMER_ID) AS "Customers" FROM CUSTOMER GROUP BY EMPLOYEE_ID ORDER BY EMPLOYEE_ID ASC;

PROMPT *** Most Popular Product for Companies in California ***
SELECT PRODUCT_ID AS "Product ID", PRODUCT_NAME AS "Product Name" FROM PRODUCT WHERE PRODUCT_ID = (SELECT PRODUCT_ID FROM INVOICE WHERE QUANTITY = (SELECT MAX(QUANTITY) FROM INVOICE) AND INVOICE_NUM IN (SELECT INVOICE_NUM FROM ORDERS WHERE CUSTOMER_ID IN (SELECT CUSTOMER_ID FROM CUSTOMER WHERE CUSTOMER_STATE = 'CA')));