SET ECHO OFF
SET VERIFY OFF
SET HEADING OFF

PROMPT ***** Find Orders by Employee ID *****
ACCEPT eID PROMPT "Enter employee ID: ";
SELECT EMPLOYEE_ID AS "ID",EMPLOYEE_FNAME||' '||EMPLOYEE_LNAME AS "Name" FROM EMPLOYEE WHERE EMPLOYEE_ID = '&eID';
PROMPT Orders:
SELECT ORDERS.INVOICE_NUM AS "Invoice#", PRODUCT_NAME AS "Product", CUSTOMER_COMPANY AS "CUSTOMER", QUANTITY AS "Qty", ORDER_DATE AS "Date", TO_CHAR(QUANTITY * PRODUCT_PPU, '$999,999.99') AS "Total" FROM ORDERS, CUSTOMER, PRODUCT, INVOICE WHERE CUSTOMER.EMPLOYEE_ID = '&eID' AND ORDERS.INVOICE_NUM = INVOICE.INVOICE_NUM AND PRODUCT.PRODUCT_ID = INVOICE.PRODUCT_ID AND ORDERS.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID ORDER BY ORDER_DATE ASC;

PROMPT 
PROMPT ***** Customer Lookup *****
ACCEPT vID PROMPT 'Please enter Customer ID: ';
PROMPT
PROMPT 'Thank you!'
PROMPT
SELECT 'COMPANY Name: ' || CUSTOMER_COMPANY
FROM CUSTOMER
WHERE  CUSTOMER_ID = '&vID';
SELECT 'Contact: ' || CUSTOMER_CONTACT
FROM CUSTOMER
WHERE  CUSTOMER_ID = '&vID';
SELECT 'Phone: ' || '(' || SUBSTR(CUSTOMER_PHONE,1,3) || ') ' || SUBSTR(CUSTOMER_PHONE,4,3) || '-' || SUBSTR(CUSTOMER_PHONE,7,4)
FROM CUSTOMER
WHERE  CUSTOMER_ID = '&vID';
SELECT 'Address: ' ||  CUSTOMER_ADDRESS || ' ' || CUSTOMER_CITY || ', ' || CUSTOMER_STATE || ' ' || CUSTOMER_ZIP
FROM CUSTOMER
WHERE  CUSTOMER_ID = '&vID';

PROMPT 
PROMPT ***** Employee Lookup *****
ACCEPT vID PROMPT 'Please enter employee ID: ';
PROMPT
PROMPT 'Thank you!'
PROMPT
SELECT 'Name: ' || EMPLOYEE_LNAME || ', ' || EMPLOYEE_FNAME
FROM EMPLOYEE
WHERE  EMPLOYEE_ID = '&vID';
SELECT 'Phone: ' || '(' || SUBSTR(EMPLOYEE_PHONE,1,3) || ') ' || SUBSTR(EMPLOYEE_PHONE,4,3) || '-' || SUBSTR(EMPLOYEE_PHONE,7,4)
FROM EMPLOYEE
WHERE EMPLOYEE_ID = '&vID';
SELECT 'Address: ' ||  EMPLOYEE_ADDRESS || ' ' || EMPLOYEE_CITY || ', ' || EMPLOYEE_STATE || ' ' || EMPLOYEE_ZIP
FROM EMPLOYEE
WHERE EMPLOYEE_ID = '&vID';
SELECT 'Date of Hire: ' || EMPLOYEE_HIREDATE
FROM EMPLOYEE
WHERE EMPLOYEE_ID = '&vID';
PROMPT Assigned Customers:
SELECT C.CUSTOMER_COMPANY
FROM EMPLOYEE E, CUSTOMER C
WHERE E.EMPLOYEE_ID = C.EMPLOYEE_ID AND E.EMPLOYEE_ID = '&vID';

PROMPT
PROMPT ***** Invoice Lookup *****
ACCEPT iID PROMPT 'Enter invoice number: ';
SELECT 'Invoice#: ' || INVOICE_NUM FROM ORDERS WHERE INVOICE_NUM = '&iID';
SELECT 'Date: ' || ORDER_DATE FROM ORDERS WHERE INVOICE_NUM = '&iID';
SELECT 'Customer: ' || CUSTOMER_COMPANY FROM ORDERS,CUSTOMER WHERE INVOICE_NUM = '&iID' AND ORDERS.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID;
PROMPT Product ID | Product Name | Product Description | Quantity | Total Cost
SELECT INVOICE.PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, QUANTITY, TO_CHAR(QUANTITY * PRODUCT_PPU,'$999,999,999.99') FROM INVOICE, PRODUCT WHERE INVOICE_NUM = '&iID' AND INVOICE.PRODUCT_ID = PRODUCT.PRODUCT_ID;